package com.redhat.errata.errata_user_settings;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class approval implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public approval() {
    }

}